# Generated by Django 2.2.2 on 2019-07-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, help_text='Current save date.', verbose_name='Date')),
                ('end_date', models.DateField(help_text='Enter the end date.', verbose_name='End date')),
                ('note', models.TextField(help_text='Enter the note.', verbose_name='Note')),
                ('attached', models.FileField(blank=True, help_text='Enter the attached.', null=True, upload_to='attacheds/', verbose_name='Attached')),
                ('task', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='Is a task?', max_length=10, verbose_name='Task')),
                ('tags', models.TextField(help_text='Enter the tags separated by comma.', verbose_name='Tags')),
                ('type_field', models.CharField(help_text="Enter the note's type.", max_length=150, verbose_name='Type')),
                ('users', models.ManyToManyField(blank=True, help_text='Enter the users.', null=True, to='user.User', verbose_name='Users')),
            ],
        ),
    ]
